name: "Python Container Action Template"
description: "Get started with Python Container actions"
author: "Arno Richter"
inputs:
  SERVER:
    description: "SSH server (required)"
    required: true 
    type: string
  PORT:
    description: "SSH port, default is 22"
    default: 22
  USER:
    description: "SSH username (required)"
    required: true 
    type: string
  PASS:
    description: "SSH key (required)"
    required: true 
    type: string
  SOURCE:
    description: "source dir"
    required: false
    default: .
    type: string
  TARGET:
    description: "target dir on the server (default is $HOME)"
    required: true
    default: ~
    type: string
outputs:
  myOutput:
    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"
