name: "Python Container Action Template"
description: "Get started with Python Container actions"
author: "Arno Richter"
inputs:
  SERVER:
    description: "SSH server (required)"
    default: 22
  PORT:
    description: "SSH port, default is 22"
    default: 22
  USERNAME:
    description: "SSH username (required)"
    default: ""
  PASS:
    description: "SSH key (required)"
    default: ""
outputs:
  myOutput:
    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"
